package com.example.projectsoftuni.model.entity.enums;

public enum ClientEnum {
    AKVILOD_OOD,
    ET_ZORNICA_TEODOR_BONCHEV,
    DUNAPACK_RODINA,
    DJONS_COMPANY,
    EKO_FARM,
    ZORNICA_KOMERS_OOD,
    KRICIYA_EOOD,
    SL_KOMERS_EOOD,
    MARVAS_90_FRENKEVI_I_SIE_SD,
    DION_OOD_RUSE,
    ZP_HASAN_ESREFOV_HASANOV,
    ZOURAS_FARM_S_A,
    IMAJ_FRESH_IMPORT_EKSPORT_SRL,
    RAFUUD_SPOLKA,
    SARAY_HANDELS_GMBH
}
